import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className} data-theme="light">
      <body>
        <header className="border-b-2 border-[#E5E8EB]">
          <Navbar />
        </header>
        <main className="max-w-7xl mx-auto px-2 xl:px-0">{children}</main>
      </body>
    </html>
  );
}
