import { Poppins } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/lib/SessionProvider";
import { AblyProvider } from "@/lib/AblyProvider";
import "@copilotkit/react-ui/styles.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "One-Orbit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en" data-theme="light">
      <body className={poppins.className}>
        <AuthProvider session={session}>
          <AblyProvider>
          {/* <CopilotKit  publicApiKey="ck_pub_c73ee7f55951cccd8e9fbe517711a8a1">
           
          </CopilotKit> */}
             <Toaster></Toaster>
            <header className="bg-linear-to-br from-gray-50 via-blue-50 to-indigo-100 dark:from-gray-900 dark:via-blue-900/20 dark:to-indigo-900/20 sticky top-0 z-60">
              <Navbar />
            </header>
            <div className="bg-linear-to-br from-gray-50 to-indigo-100 dark-bg overflow-hidden">
              <main className="w-full mx-auto px-2 xl:px-0">{children}</main>
            </div>
            <Footer />
          </AblyProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
